language: php

sudo: false

dist: trusty

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

before_script:
    - mkdir -p build/logs

script:
    - composer update --prefer-dist --no-interaction --no-progress
    - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml
    - if [ "${TRAVIS_PHP_VERSION}" != 'hhvm' ] && [ "${TRAVIS_PHP_VERSION}" != 'nightly' ]; then travis_retry wget -q https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && travis_retry php coveralls.phar -v; fi

notifications:
    email:
        - antalaron@antalaron.hu

cache:
    directories:
        - $HOME/.composer/cache
